### ISSUE TITLE
Issue when using conllu_to_odin function

### ISSUE THREAD

**Issue by AvivWn** [allenai/pybart#20]
Hi
Nice work!

I encountered an issue when I tried to use your conllu to odin format converter on pybart parsings.
I added the BART pipe to the spaCy parser's pipeline, after creating an instance of your converter:
converter = Converter()
nlp.add_pipe(converter, name="BART")

Then, I got the parsing of my sentence.
doc = nlp(sentence)

Finally, I used the conllu_to_odin funciton, like so:
odin_formated_doc = cw.conllu_to_odin(doc, is_basic=True, push_new_to_end=False)

This resulted with an error, which I couldn't resolve.
Maybe doc isn't the right input for conllu_to_odin?

**Comment by aryehgigi** [comment]
Thanks for sharing!

Yes, doc isn't the correct format to use here, the short answer is simply do:
odin_formated_doc = cw.conllu_to_odin(converter.get_parsed_doc(), is_basic=True, push_new_to_end=False)

The converter's class holds the information of the doc, so you could request it in the future in the format that resmbles conllu (more of a parsed conllu format), exactly for these types of usages (i.e. conllu_to_odin).

**Comment by AvivWn** [comment]
Cool thanks!
Now it is working.
