### ISSUE TITLE
PyBart crash with en_ud_model_trf

### ISSUE THREAD

**Issue by RoyiRa** [allenai/pybart#35]
Hey!

When using the model "en_ud_model_trf" and the following sentence:

_She was convicted of selling unregistered securities in Florida, and of unlawful phone calls in Ohio._

PyBart produces the following error: 

_Traceback (most recent call last):
  File "/Users/royi/missing_elements_exploration/test.py", line 41, in <module>
    print([doc[t.i].text for t in edge.head.tokens], f" --{edge.label_}-> ",
  File "spacy/tokens/graph.pyx", line 119, in spacy.tokens.graph.Node.tokens.__get__
  File "spacy/tokens/doc.pyx", line 461, in spacy.tokens.doc.Doc.__getitem__
  File "spacy/tokens/token.pxd", line 23, in spacy.tokens.token.Token.cinit
IndexError: [E040] Attempt to access token at 19, max length 18._

The error can  also be reproduced with the sentence mentioned in a previous issue:

_London is home to many museums, galleries, and other institutions, many of which are free of admission charges and are major tourist attractions as well as playing a research role._

With the traceback:

_Traceback (most recent call last):
  File "/Users/royi/missing_elements_exploration/test.py", line 42, in <module>
    print([doc[t.i].text for t in edge.head.tokens], f" --{edge.label_}-> ",
  File "spacy/tokens/graph.pyx", line 119, in spacy.tokens.graph.Node.tokens.__get__
  File "spacy/tokens/doc.pyx", line 460, in spacy.tokens.doc.Doc.__getitem__
  File "spacy/tokens/doc.pyx", line 45, in spacy.tokens.doc.bounds_check
IndexError: [E026] Error accessing token at position 39: out of bounds in Doc of length 34._

I am running version 3.2.2.
Also, the error does not occur if I use "en_core_web_trf", however, in that case I get a different graph from what PyBart-demo produces.

Thanks

**Comment by aryehgigi** [comment]
hey @RoyiRa, Are you sure you are running version 3.2.2? I can't reproduce. This is weird especially because 3.2.2 fixed this issue.
See for example the demo, it doesn't crash when running these sentences (and it is running version 3.2.2)
can you add `print(pybart.__version__)` to your code and add the output here?

**Comment by RoyiRa** [comment]
Is that what you're looking for? 
I'd like to reiterate, the bug doesn't happen when using en_core_web_trf, but it does for en_ud_model_trf.

![Screen Shot 2021-05-03 at 15 38 54](https://user-images.githubusercontent.com/37896343/116876781-abbd2800-ac25-11eb-9c18-1382316e5edb.png)

**Comment by aryehgigi** [comment]
It seems the example from the readme (which you have used) was not up to date. so I have updated it now, so it wont fail now (if you use the updated code).
Thanks a lot for your involvement.
