### ISSUE TITLE
pybart to odinson representation mapping

### ISSUE THREAD

**Issue by amirj** [allenai/pybart#39]
Hi,

Thanks for sharing this valuable package.
Could you provide some hints how pybart representation can be indexed and retrieved via [odinson](https://github.com/lum-ai/odinson) please? 
Is there any tool to convert pybart representation to odinson documents?

**Comment by aryehgigi** [comment]
Hey @amirj
Thanks for using this package, there are 2 main API's which will give you either CONLL-U format or spacy doc. 
IIRC, odinson format is actually a json representing the dependency graph/tree, so it is possible to write a conversion

**Comment by aryehgigi** [comment]
Hey @amirj 
(NOTE -  if youve seen the deleted message please ignore it, this is the updated one)
Happy to contribute, and im happy to see you are using this work.
Im not an odinson expert, but i did add an odin format conversion as i needed it for my a demo using [TAG](https://github.com/CreativeCodingLab/TextAnnotationGraphs) which requires odin format.
It is not a formal API but it exists, so you can try something like this:

```
from pybart.api import Converter
import pybart.conllu_wrapper as cw
extra_con = Converter(CHOOSE_PARAMS)
odin_plus_out = cw.conllu_to_odin(extra_con.get_converted_sents(), push_new_to_end=False)
```

**Comment by aryehgigi** [comment]
stale
